### ISSUE TITLE
Commands fail and instruct user to run python

### ISSUE THREAD

**Issue by neural-loop** [visioninit/aimm#20]
![image](https://user-images.githubusercontent.com/654993/205708393-4d8bc88e-078d-488e-952f-65e40f9c9d72.png)

![image](https://user-images.githubusercontent.com/654993/205708490-60e85d55-11cd-413c-a6e7-9a985792fc33.png)

**Comment by Rayrsn** [comment]
might be happening because of the way pynsist handles `entry_point`, possible solution is to use `script` instead

**Comment by neural-loop** [comment]
Doesnt seem to be different.

![image](https://user-images.githubusercontent.com/654993/206860843-15e815b8-ee52-45a5-bf88-853689a91997.png)
